Scribble-Board-Region: 'scribble_board'

Scribble-Arena-Region: 'scribble'

Scribble-Drawing-Region: 'scribble_player'

Scribble-Drawing-Portal-Enter: 'scribble_drawing_lodge'

Scribble-Drawing-Portal-Exit: 'scribble_forceexit_lodge'

Scribble-List:
  - test