name: CVScribble
version: 2.0
main: org.cubeville.cvscribble.CVScribble
description: Scribble minigame plugin
author: FrediW,ToeMan_
depend: [WorldEdit,WorldGuard,CVTools,CVChat,CVPortal,CVMenu]
api-version: 1.16

commands:
  scribbleclear:
    description: Clear the scribble board
    usage: /scribbleclear
    permission: cvscribble.scribbleclear

  cvscribble:
    aliases: scribble
    permission: cvscribble.admin

permissions:
  cvscribble.admin:
    description: Gives player access to every cvscribble command
    default: op
